import { Metadata } from "next";
import ContentLayout from "@/components/ContentLayout";

export const metadata: Metadata = {
  title: "Terms of Use",
  description:
    "Terms of Use for LexEU — AI-powered legal information service for EU law. Read our terms before using the platform.",
  alternates: { canonical: "https://www.lexeu.ai/terms/" },
};

const breadcrumbs = [{ label: "Terms of Use", href: "/terms/" }];

export default function TermsPage() {
  return (
    <ContentLayout
      breadcrumbs={breadcrumbs}
      title="Terms of Use"
      subtitle="Please read these terms carefully before using the LexEU service."
      article={{
        title: "Terms of Use",
        description:
          "Terms of Use for LexEU — AI-powered legal information service for EU law.",
        url: "/terms/",
        datePublished: "2026-03-01",
        dateModified: "2026-03-24",
      }}
    >
      <div className="legal-prose">
        <p>
          <strong>Last updated: March 2026</strong>
        </p>

        <h2>1. Introduction</h2>
        <p>
          These Terms of Use (&ldquo;Terms&rdquo;) govern your access to and use of the
          LexEU website and AI-powered legal information service available at{" "}
          <a href="https://www.lexeu.ai">www.lexeu.ai</a> (&ldquo;Service&rdquo;). Please
          read these Terms carefully before using the Service.
        </p>
        <p>
          By accessing or using the Service, you confirm that you have read,
          understood, and agree to be bound by these Terms. If you do not agree,
          you must not use the Service.
        </p>

        <h2>2. Who We Are</h2>
        <p>The Service is operated by:</p>
        <p>
          <strong>LexEU s.r.o.</strong>
          <br />
          Galvaniho 33A, 821 04 Bratislava - Ružinov, Slovak Republic
          <br />
          IČO: 56316585 | DIČ: 2122278818 | IČ DPH: SK2122278818
          <br />
          Email: <a href="mailto:info@lexeu.ai">info@lexeu.ai</a>
        </p>
        <p>
          References to &ldquo;LexEU,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo; in these Terms
          refer to LexEU s.r.o.
        </p>

        <h2>3. Acceptance of Terms</h2>
        <p>
          By creating an account, purchasing a subscription, or using any part of
          the Service, you agree to these Terms and our{" "}
          <a href="/privacy/">Privacy Policy</a> and{" "}
          <a href="/cookies/">Cookie Policy</a>. These documents form the
          complete agreement between you and LexEU s.r.o. regarding your use of
          the Service.
        </p>

        <h2>4. Eligibility</h2>
        <p>
          You must be at least <strong>18 years of age</strong> to use the
          Service. By using the Service, you confirm that you are 18 or older. If
          you are using the Service on behalf of a business or organization, you
          represent that you have authority to bind that entity to these Terms.
        </p>

        <h2>5. Description of Service</h2>
        <p>
          LexEU is an AI-powered legal information platform. The Service allows
          users to submit legal questions and receive AI-generated informational
          responses based on legislation from:
        </p>
        <ul>
          <li>Austria</li>
          <li>Germany</li>
          <li>Italy</li>
          <li>Poland</li>
          <li>Serbia</li>
          <li>European Union (EU legislation and directives)</li>
        </ul>
        <p>
          Responses are generated by artificial intelligence models and include
          references to applicable laws, directives, and regulations.
        </p>
        <p>
          <strong>
            LexEU is not a law firm. The Service is provided for informational
            purposes only.
          </strong>
        </p>

        <h2>
          6. Important Disclaimer — Legal Information, Not Legal Advice
        </h2>
        <p>This section is important. Please read it carefully.</p>
        <p>
          <strong>6.1</strong> The content provided through LexEU constitutes{" "}
          <strong>legal information</strong>, not{" "}
          <strong>legal advice</strong>. There is a critical distinction:
        </p>
        <ul>
          <li>
            <strong>Legal information</strong> explains what the law says, in
            general terms.
          </li>
          <li>
            <strong>Legal advice</strong> applies the law to your specific
            situation and is provided by a qualified attorney who represents you.
          </li>
        </ul>
        <p>
          <strong>6.2</strong> Using the Service{" "}
          <strong>does not create an attorney-client relationship</strong> between
          you and LexEU s.r.o., or between you and any attorney.
        </p>
        <p>
          <strong>6.3</strong> AI-generated responses may not reflect the most
          current state of the law, may contain inaccuracies, and may not account
          for your specific circumstances, local variations, or recent court
          decisions.
        </p>
        <p>
          <strong>6.4</strong> You should not rely solely on LexEU responses to
          make legal decisions. For any matter with significant legal
          consequences, you should consult a qualified attorney licensed in the
          relevant jurisdiction.
        </p>
        <p>
          <strong>6.5</strong> Nothing in the Service constitutes legal
          representation, and LexEU s.r.o. does not represent users in any legal
          proceeding.
        </p>

        <h2>7. User Accounts</h2>
        <p>
          <strong>7.1 Registration.</strong> To access the Service, you must
          create an account by providing accurate and complete information. You
          agree to keep your account information current.
        </p>
        <p>
          <strong>7.2 Account Security.</strong> You are responsible for
          maintaining the confidentiality of your login credentials. You must
          notify us immediately at{" "}
          <a href="mailto:info@lexeu.ai">info@lexeu.ai</a> if you become aware
          of any unauthorized use of your account.
        </p>
        <p>
          <strong>7.3 One Account Per Person.</strong> Each person may maintain
          only one account. Sharing account credentials with others is not
          permitted.
        </p>

        <h2>8. Acceptable Use</h2>
        <p>You agree not to use the Service to:</p>
        <ul>
          <li>Submit false, misleading, or fraudulent information</li>
          <li>Violate any applicable law or regulation</li>
          <li>
            Attempt to reverse-engineer, copy, or reproduce the AI models or
            algorithms underlying the Service
          </li>
          <li>
            Scrape, harvest, or systematically collect content from the Service
          </li>
          <li>
            Interfere with or disrupt the Service&rsquo;s infrastructure, servers, or
            networks
          </li>
          <li>Use the Service for any purpose that could harm minors</li>
          <li>Harass, abuse, or harm other users or third parties</li>
          <li>Attempt to circumvent any security or access controls</li>
          <li>
            Resell, sublicense, or commercialize the Service without our written
            consent
          </li>
        </ul>
        <p>
          We reserve the right to suspend or terminate accounts that violate
          these provisions.
        </p>

        <h2>9. Payment Terms</h2>
        <p>
          <strong>9.1 Pricing.</strong> The Service is provided on a paid basis.
          Current pricing plans and subscription tiers are listed on the LexEU
          website at <a href="https://www.lexeu.ai">www.lexeu.ai</a>. Prices are
          displayed in Euros (€) and include applicable VAT where required by
          law.
        </p>
        <p>
          <strong>9.2 Payment Processing.</strong> Payments are processed by our
          third-party payment provider. Your payment details are collected and
          stored by the payment provider, not by LexEU s.r.o. By making a
          purchase, you agree to the payment provider&rsquo;s terms.
        </p>
        <p>
          <strong>9.3 Billing.</strong> Subscription fees are charged at the time
          of purchase. Where you purchase a recurring subscription, billing
          occurs automatically at the start of each billing period.
        </p>
        <p>
          <strong>9.4 Refunds.</strong> Due to the digital nature of the Service,
          we do not offer refunds once questions have been submitted. If you have
          a billing concern, please contact us at{" "}
          <a href="mailto:info@lexeu.ai">info@lexeu.ai</a> and we will review
          your case.
        </p>
        <p>
          <strong>9.5 Price Changes.</strong> We may change pricing with
          reasonable notice. Continued use of the Service after a price change
          takes effect constitutes acceptance of the new pricing.
        </p>

        <h2>10. Intellectual Property</h2>
        <p>
          <strong>10.1</strong> The LexEU platform, including its design,
          software, trademarks, and underlying technology, is owned by or
          licensed to LexEU s.r.o. All rights are reserved.
        </p>
        <p>
          <strong>10.2</strong> Legal texts, directives, and legislation
          referenced in AI responses are public domain or third-party materials
          and are not claimed by LexEU s.r.o.
        </p>
        <p>
          <strong>10.3</strong> You retain ownership of the legal questions you
          submit. By submitting queries, you grant LexEU s.r.o. a limited,
          non-exclusive license to process that content for the purpose of
          providing the Service and, in anonymized form, for improving the
          Service (see also our <a href="/privacy/">Privacy Policy</a>).
        </p>
        <p>
          <strong>10.4</strong> You may not reproduce, distribute, or create
          derivative works from LexEU content without our written permission.
        </p>

        <h2>11. AI-Generated Content</h2>
        <p>
          <strong>11.1</strong> Responses are generated by AI models. While we
          take care to build a reliable service, AI systems can produce errors,
          hallucinations, or outdated information.
        </p>
        <p>
          <strong>11.2</strong> We do not guarantee the accuracy, completeness,
          or timeliness of any AI-generated response.
        </p>
        <p>
          <strong>11.3</strong> Citation of legislation in responses is provided
          for reference. You should verify the current version of any law through
          official government or legislative sources.
        </p>

        <h2>12. Limitation of Liability</h2>
        <p>
          <strong>12.1</strong> To the maximum extent permitted by applicable law,
          LexEU s.r.o. and its officers, employees, and agents are not liable
          for:
        </p>
        <ul>
          <li>
            Any loss or damage arising from your reliance on AI-generated legal
            information
          </li>
          <li>
            Any legal decisions made on the basis of Service responses
          </li>
          <li>Any indirect, incidental, special, or consequential damages</li>
          <li>Loss of profits, data, or business opportunities</li>
        </ul>
        <p>
          <strong>12.2</strong> Our total liability to you for any claim arising
          from the Service shall not exceed the amount you paid to us in the
          three (3) months preceding the claim.
        </p>
        <p>
          <strong>12.3</strong> Nothing in these Terms excludes liability for
          death or personal injury caused by our negligence, fraud, or any
          liability that cannot be excluded by law.
        </p>
        <p>
          <strong>12.4</strong> EU consumer law rights are not affected by these
          Terms.
        </p>

        <h2>13. Indemnification</h2>
        <p>
          You agree to indemnify and hold harmless LexEU s.r.o. from any claims,
          damages, or expenses (including reasonable legal fees) arising from
          your misuse of the Service or your breach of these Terms.
        </p>

        <h2>14. Third-Party Services</h2>
        <p>
          The Service may integrate with or link to third-party services (such as
          payment processors). We are not responsible for the content, privacy
          practices, or reliability of third-party services. Use of third-party
          services is governed by their respective terms and privacy policies.
        </p>

        <h2>15. Changes to These Terms</h2>
        <p>
          We may update these Terms from time to time. We will notify you of
          material changes by email or by posting a notice on the website. Your
          continued use of the Service after the effective date of updated Terms
          constitutes acceptance. If you do not agree with changes, you may stop
          using the Service and close your account.
        </p>

        <h2>16. Termination</h2>
        <p>
          <strong>16.1</strong> You may stop using the Service and close your
          account at any time by contacting us at{" "}
          <a href="mailto:info@lexeu.ai">info@lexeu.ai</a>.
        </p>
        <p>
          <strong>16.2</strong> We may suspend or terminate your access to the
          Service with or without notice if you breach these Terms, if required
          by law, or if we discontinue the Service.
        </p>
        <p>
          <strong>16.3</strong> Upon termination, your right to use the Service
          ends immediately. Provisions of these Terms that by their nature should
          survive termination will remain in effect.
        </p>

        <h2>17. Governing Law and Dispute Resolution</h2>
        <p>
          <strong>17.1 Governing Law.</strong> These Terms are governed by the
          laws of the <strong>Slovak Republic</strong>, without regard to its
          conflict-of-laws rules.
        </p>
        <p>
          <strong>17.2 Disputes.</strong> Any dispute arising from or relating to
          these Terms or the Service shall first be attempted to be resolved
          through good-faith negotiation. If a resolution is not reached within
          30 days, disputes shall be subject to the exclusive jurisdiction of the{" "}
          <strong>competent courts of the Slovak Republic</strong>. For
          commercial matters, Mestský súd Bratislava III has first-instance
          jurisdiction.
        </p>
        <p>
          <strong>17.3 Consumer ADR.</strong> If you are a consumer and a dispute
          cannot be resolved directly, you may contact the{" "}
          <strong>Slovenská obchodná inšpekcia (SOI)</strong> — the Slovak Trade
          Inspection — for alternative dispute resolution. Website:{" "}
          <a href="https://www.soi.sk">https://www.soi.sk</a>.
        </p>
        <p>
          <strong>17.4 EU Online Dispute Resolution.</strong> If you are a
          consumer based in the European Union, you may also use the European
          Commission&rsquo;s Online Dispute Resolution (ODR) platform to resolve
          disputes:{" "}
          <a href="https://ec.europa.eu/consumers/odr">
            https://ec.europa.eu/consumers/odr
          </a>
          . Our contact email for ODR purposes is:{" "}
          <a href="mailto:info@lexeu.ai">info@lexeu.ai</a>.
        </p>
        <p>
          <strong>17.5 Consumer Rights.</strong> Nothing in these Terms limits
          your rights as a consumer under applicable EU or national consumer
          protection law.
        </p>

        <h2>18. Contact Us</h2>
        <p>For questions, concerns, or support:</p>
        <p>
          <strong>LexEU s.r.o.</strong>
          <br />
          Galvaniho 33A, 821 04 Bratislava - Ružinov, Slovak Republic
          <br />
          IČO: 56316585 | DIČ: 2122278818 | IČ DPH: SK2122278818
          <br />
          Email: <a href="mailto:info@lexeu.ai">info@lexeu.ai</a>
        </p>

        <hr />
        <p>© 2026 LexEU s.r.o. All rights reserved.</p>
      </div>
    </ContentLayout>
  );
}
